tp2_grupo16/src/main/resources/templates/index.html, tp2_grupo16/src/main/resources/templates/sdpaseos.html
- creacion sdpaseos.html
- agregue el atributo lang="es" al index.html
=> creacion de la pagina de servicio de paseos.html

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/InicioController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaServicios.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Servicio.java, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/layouts/header.html, tp2_grupo16/src/main/resources/templates/nuevo_servicio.html, tp2_grupo16/src/main/resources/templates/sdpaseos.html
*mostrado en una tabla con acciones de modificar y eliminar
*esto se creo con su propia clase lista, controller, model y una pagina dedicada a un formulario
Close #37
=> Se creó el alta para la pagina de servicios

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ContactoController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Sucursal.java, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/contacto.html, tp2_grupo16/src/main/resources/templates/layouts/header.html, tp2_grupo16/src/main/resources/templates/nueva_sucursal.html, tp2_grupo16/src/main/resources/templates/sdpaseos.html, tp2_grupo16/src/main/resources/templates/sucursales.html
*se crea el alta a la pagina de sucursales añadiendo una tabla con las sucursales y las acciones de poder agregar, modificar y eliminar *correcciones en las imagenes de las sucursales
*se agrego un mensaje avisando al usuario cuando envio un mensaje en la seccion de contacto
Close #39
=> Se crea el alta a la pagina de sucursales

tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Sucursal.java
Se realizo la documentación correspondiente de los métodos de la clase Sucursal.
=> Documentacion de Clase Sucursal

tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Servicio.java
Se realizó la documentación correspondiente de la clase Servicios.
=> Documentación de la clase Servicio.

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ContactoController.java
Para un mejor manejo se creo la rama documentación para realizar la documentación y sus cambios.
=> Creación de la rama Documentación

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ProductosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/form/FormProducto.java
Se realizo la documentación correspondiente.
=> Documentacion

tp2_grupo16/pom.xml, tp2_grupo16/src/main/resources/templates/consejos_de_salud.html, tp2_grupo16/src/main/resources/templates/contacto.html, tp2_grupo16/src/main/resources/templates/index.html, tp2_grupo16/src/main/resources/templates/layouts/footer.html, tp2_grupo16/src/main/resources/templates/layouts/header.html, tp2_grupo16/src/main/resources/templates/nueva_sucursal.html, tp2_grupo16/src/main/resources/templates/nuevo-producto.html, tp2_grupo16/src/main/resources/templates/nuevo_servicio.html, tp2_grupo16/src/main/resources/templates/productos.html, tp2_grupo16/src/main/resources/templates/sdpaseos.html, tp2_grupo16/src/main/resources/templates/sucursales.html
*se agrego las dependencias de bootstrap y locator al archivo pom.xml.
*se agrego las etiquetas meta para el viewport y el link haciendo referencia al archivo Bootstrap local en el header de todas las paginas del proyecto.
Close #55
=> Implementación de Bootstrap

tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/consejos_de_salud.html, tp2_grupo16/src/main/resources/templates/contacto.html, tp2_grupo16/src/main/resources/templates/index.html, tp2_grupo16/src/main/resources/templates/layouts/header.html, tp2_grupo16/src/main/resources/templates/nueva_sucursal.html, tp2_grupo16/src/main/resources/templates/nuevo-producto.html, tp2_grupo16/src/main/resources/templates/nuevo_servicio.html, tp2_grupo16/src/main/resources/templates/productos.html, tp2_grupo16/src/main/resources/templates/sdpaseos.html, tp2_grupo16/src/main/resources/templates/sucursales.html
Se añadio el diseño responsivo a todas las paginas
*se modificaron clases en los tags de algunas paginas *se modificaron los estilos en las paginas de productos y consejos de salud
Close #57
=> Diseño responsivo

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaServicios.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Servicio.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Sucursal.java, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/consejos_de_salud.html, tp2_grupo16/src/main/resources/templates/nueva_sucursal.html, tp2_grupo16/src/main/resources/templates/nuevo-producto.html, tp2_grupo16/src/main/resources/templates/nuevo_servicio.html, tp2_grupo16/src/main/resources/templates/productos.html, tp2_grupo16/src/main/resources/templates/sucursales.html
*adaptacion de las clases Producto, ListaProducto, Sucursales, ListaSucursales con Component
*adaptacion de autowired en los controladores de productos y sucursales *se solucionaron tambien algunos errores con bootstrap para un mejor diseño
*modificacion de algunos estilos en css
Close #59
=> Autowired y Component en sucursales y servicios

tp2_grupo16/pom.xml
=> Se agrego dependencias de validación en el archivo pom.xml

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Sucursal.java, tp2_grupo16/src/main/resources/templates/nueva_sucursal.html, tp2_grupo16/src/main/resources/templates/sucursales.html
*se añadio el poder agregar imagenes mediante url al registrar/modificar una sucursal y poder reflejarse a la vista del usuario 
*se añadio el atributo 'estado' que recibe los valores de 'Abierto' y 'Cerrado' para las sucursales
*ahora al agregar una sucursal en la tabla de sucursales automaticamente en caso de que la sucursal se encuentre en estado 'Abierto' se vera reflejado en una card representativa de lo contradio si esta en estado 'Cerrado' se ocultara a la vista
Close #61
=> Funcionalidad a las cards de Sucursales

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaServicios.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Servicio.java, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/nuevo_servicio.html, tp2_grupo16/src/main/resources/templates/sdpaseos.html, tp2_grupo16/src/main/resources/templates/sucursales.html
*se agrego un nuevo atributo: la hora
*se dio mas informacion sobre las personas encargadas de los servicios en la tabla de informacion
*se modificaron algunas clases en los html
*se modificaron algunas estilos de css para un mejor aspecto visual
Close #65
=> Funcionalidad a la pag Servicios

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Servicio.java, tp2_grupo16/src/main/resources/templates/nuevo_servicio.html
=> Validación de los servicios, se agrego también mensajes de error.

tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IConsejoService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IProductoService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IServicioService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
Se creo el paquete ar.unju.edu.fi.service para la capa Service y dentro se crearon las interfaces: IProductoService, ISucursalService, IConsejoService, IServicioService.
Se crearon los métodos abstractos: listar, guardar, modificar, eliminar, buscar y recuperar un objeto del model, en cada interfaz.
Closes #74
=> Implementación de interfaces en la capa Service

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ProductosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Servicio.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Sucursal.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IConsejoService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IProductoService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IServicioService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/ISucursalService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/productos.html, tp2_grupo16/src/main/resources/templates/sucursales.html
Se inyecto los servicios a los controllers de las paginas de productos, servicios y de sucursales
se documento las metodos de las interfaces de servicios de las paginas se corrigieron los colores de los form para mejor visualizacion de los errores de validacion
Close #76
=> implementacion de los servicios a los controllers

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ConsejosDeSaludController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaConsejos.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Consejo.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IConsejoService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/consejos_de_salud.html, tp2_grupo16/src/main/resources/templates/nuevo_consejo.html
Se implementa el ABM de la pagina consejos, también se añade estilos y sus correspondientes implementaciones de servicios.
Closes #78
=> Se realiza el abm de la pagina consejos y componentes de servicio.

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ConsejosDeSaludController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ProductosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/nueva_sucursal.html, tp2_grupo16/src/main/resources/templates/nuevo-producto.html, tp2_grupo16/src/main/resources/templates/nuevo_consejo.html, tp2_grupo16/src/main/resources/templates/nuevo_servicio.html
se eliminaron algunas lineas de los controllers
en el html se reemplazo el th:disabled por th:readonly para cuando al dar de alta el valor dentro del input no se pierda y asi no tener que utilizar una variable auxiliar como el "<objeto>Encontrado" en todos los controllers
se creo la clase css field-disabled para los input que estan modo de solo lectura para indicar al usuario que el campo no puede ser modificado
Close #80
=> pequeña correcion de validaciones

tp2_grupo16/pom.xml, tp2_grupo16/src/main/resources/application.properties
Se realiza la incorporación de las dependencias correspondientes a JPA y MySQL
=> Incorporacion de dependencisa JPA

tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Consejo.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Contacto.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Producto.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Servicio.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
Se realiza el mapeo de entidades
=> Renombre de paquete y mapeo de clases

tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Producto.java
=> Actualización clase Producto

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ProductosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/model/Producto.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java, tp2_grupo16/src/main/resources/templates/nuevo-producto.html, tp2_grupo16/src/main/resources/templates/productos.html
se hizo la correccion de la pagina de productos, ahora cuando se da de alta un producto dependiendo de su categoria se coloca el producto en la seccion correspondiente
tambien ahora en el formulario se puede agregar la url de una imagen de internet para el producto
Close #92
=> Correcion de la pagina de productos

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/GestionController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Provincia.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Sucursal.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/repository/IProvinciaRepository.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/repository/ISucursalRepository.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IProvinciaService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/ISucursalService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/ProvinciaServiceImp.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java, tp2_grupo16/src/main/resources/application.properties, tp2_grupo16/src/main/resources/static/css/estilos.css, tp2_grupo16/src/main/resources/templates/gestion.html, tp2_grupo16/src/main/resources/templates/layouts/header.html, tp2_grupo16/src/main/resources/templates/nueva_sucursal.html, tp2_grupo16/src/main/resources/templates/sucursales.html
se agrega el mapeo de la pagina sucursal a la base de datos. Tambien se puede filtrar entre dos fechas. Se creo la pagina de gestion. Close #94
=> Bd de sucursales

tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Servicio.java
Se realiza el mapeo en la clase Servicios.
Closes #86
=> Mapeo de la clase Servicio

tp2_grupo16/src/main/java/ar/edu/unju/fi/controller/ServicioDePaseosController.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/entity/Servicio.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/repository/IServicioRepository.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/IServicioService.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java, tp2_grupo16/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceMysqlImp.java
Se realizo la actualizacion de las clases Servicio para poder cargar la tabla de la BD.
Closes #98
=> Actualización de clases para la carga de la tabla de BD
